/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

import com.Dao.DaoAsignacion;
import com.Dao.DaoEmpleado;
import com.Dao.DaoRRHH;
import com.modelo.Asignacion;
import com.modelo.Empleado;
import com.modelo.MateriaPrima;
import com.modelo.RRHH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JC
 */
public class FrmAsignacionRRHH extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAsignacionRRHH
     */
    public FrmAsignacionRRHH() throws Exception {
        initComponents();
        tablaAsignacion();
        cargarComboRRHH(cmbRRHH, drh.mostrarRRHH());
        cargarComboEmp(cmbEmpleado, de.mostrarEmpleado());
    }
    
    RRHH rh = new RRHH();
    Empleado em = new Empleado();
    DaoRRHH drh = new DaoRRHH();
    DaoEmpleado de = new DaoEmpleado();
    DaoAsignacion da = new DaoAsignacion();
    Asignacion a = new Asignacion();

    private void cargarComboRRHH(JComboBox combo,
            ArrayList<RRHH> list) throws Exception {

        for (RRHH item : list) {
            combo.addItem(new ComboItem(item.getIdRRHH(), 
                    item.getNombreRRHH()));
        }

    }
    
    private void cargarComboEmp(JComboBox combo,
            ArrayList<Empleado> list) throws Exception {

        for (Empleado item : list) {
            combo.addItem(new ComboItem(item.getIdEmp(), 
                    item.getNombreEmp()));
        }

    }
    
     public void tablaAsignacion(){
        String [] cols = {"Código RRHH","Código Empleado"};
        Object[] obj = new Object[2];
        DefaultTableModel tabla = new DefaultTableModel(null, cols);
        List ls;
        
        try {
            ls = da.mostrarAsignacion();
            for (int i = 0; i <ls.size(); i++) {
                a = (Asignacion)ls.get(i);
                obj[0] = a.getId_RRHH();
                obj[1] = a.getId_Empleado();
               
                
                tabla.addRow(obj);
            }
            
            
            this.jTable1.setModel(tabla);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al mostrar datos de la empleado "+e.toString());
        }
            
    }
     
     public void insertar(){
        
        try {
            ComboItem item = new ComboItem();
       String rh = cmbRRHH.getSelectedItem().toString();
       
        for (int i = 0; i < cmbRRHH.getItemCount(); i++) {
            if (rh.equals(cmbRRHH.getItemAt(i).toString())) {
                item = cmbRRHH.getModel().getElementAt(i);
                
            }
        }
       
       a.setId_RRHH(item.getValue());
       
       ComboItem item1 = new ComboItem();
       String em = cmbEmpleado.getSelectedItem().toString();
       
        for (int i = 0; i < cmbEmpleado.getItemCount(); i++) {
            if (em.equals(cmbEmpleado.getItemAt(i).toString())) {
                item1 = cmbEmpleado.getModel().getElementAt(i);
                
            }
        }
       
       a.setId_Empleado(item1.getValue());
            
            a.setEstado(1);
        
            da.insertarAsignacion(a);
        
        JOptionPane.showMessageDialog(null, "Datos insertados con éxito");
        
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbRRHH = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestión de RRHH");

        jLabel2.setText("RRHH");

        jLabel3.setText("Empleado");

        btnAdd.setText("Asignar");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRRHH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRRHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        insertar();
        tablaAsignacion();
    }//GEN-LAST:event_btnAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<ComboItem> cmbEmpleado;
    private javax.swing.JComboBox<ComboItem> cmbRRHH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
